#!/opt/homebrew/bin/python3
import sys,os,json
import numpy as np
from langchain_openai import OpenAIEmbeddings
from openai import OpenAI
from pinecone import Pinecone

if len(sys.argv) > 1:
  query = " ".join(sys.argv[1:])
else:
  query = sys.stdin.read()


api_key = os.getenv("PINECONE_API_KEY")
if 'OPENAI_API_KEY' not in os.environ and 'OPEN_AI_KEY' in os.environ:
 os.environ['OPENAI_API_KEY'] = os.environ['OPEN_AI_KEY']

client = OpenAI()
pc = Pinecone(api_key=api_key)
index = pc.Index("scriptures")

def translate(text,lang):
 try:
  answer = client.chat.completions.create(
    messages=[{
         "role": "user",
         "content": f"Translate the following English text to {lang}: {text}",
    }],
    model="gpt-3.5-turbo",
  )
  return answer.choices[0].message.content
 except Exception as e:
  print(f"An error occurred: {e}")
  return None

def embed(text):
 response = client.embeddings.create(
    input=text,
    model="text-embedding-ada-002"
 )
 return response.data[0].embedding

def lang_vec(q): 
 squery=translate(q,"spanish")
 mquery=translate(q,"mandarin")
 embeds=[embed(query),embed(squery),embed(mquery)]
 return np.mean(embeds,axis=0).tolist()

def bold(str):
 return f"\033[1m{str}\033[0m"
results = index.query(vector=lang_vec(query),top_k=10, include_metadata=True)
for result in results['matches']:
 meta=result['metadata'] 
 print(f"""{bold(meta['reference'])} {meta['text']}\n""")
