#!/opt/homebrew/bin/python3
import os,json
from langchain_pinecone import PineconeVectorStore
from langchain_openai import OpenAIEmbeddings
from common import wrap, bold, get_query, heading 

query = get_query()
pinecone_api_key = os.getenv("PINECONE_API_KEY")
if 'OPENAI_API_KEY' not in os.environ and 'OPEN_AI_KEY' in os.environ:
 os.environ['OPENAI_API_KEY'] = os.environ['OPEN_AI_KEY']

vectorstore = PineconeVectorStore(namespace='Chapters-1.0',index_name='content', embedding=OpenAIEmbeddings(model="text-embedding-3-large"))

for doc,score in vectorstore.similarity_search_with_relevance_scores(query,k=7):
# print(doc)
 print(f"""{bold(doc.metadata["reference"])} {doc.page_content}\n\n\n""")

print("\n")
