#!/opt/homebrew/bin/python3
import sys,os,json
import chromadb
from langchain_community.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings

if len(sys.argv) > 1:
  query = " ".join(sys.argv[1:])
else:
  query = sys.stdin.read()

print(f"query is: {query}")

db = Chroma(embedding_function=OpenAIEmbeddings(),persist_directory="scriptures_db")
for doc,score in db.similarity_search_with_relevance_scores(query,k=10):
  print(json.dumps({
    'score': score,
    'content':doc.page_content,
    'meta':doc.metadata
    },
    indent=2,
    ensure_ascii=False))

