#!/opt/homebrew/bin/python3
import os,json
import chromadb
from langchain_community.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings
from common import wrap, bold, get_query, heading
query = get_query()

db = Chroma(embedding_function=OpenAIEmbeddings(),persist_directory="scriptures_db")
for doc in db.max_marginal_relevance_search(query,k=10):
  print(json.dumps({
    'content':doc.page_content,
    'meta':doc.metadata
    },
    indent=2,
    ensure_ascii=False))

